# Generated by Django 5.1.2 on 2025-10-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ManyToManyField(null=True, related_name='g_subject', to='adminapp.subject'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kafedralar', to='adminapp.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='kafedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fanlar', to='adminapp.kafedra'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='t_subject', to='adminapp.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_group', to='adminapp.group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kafedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_kafedra', to='adminapp.kafedra'),
        ),
    ]
